#!/bin/bash

#nekropol
#City Of The Deads
#k3746ov
#
echo
#
pkg update && pkg upgrade -y
#
termux-setup-storage -y
#
echo
#
echo -e "\36[0m Installing wget package \36[0m"
#
sleep 1.0
echo
#
pkg install wget -y
#
echo
sleep 1.0
clear
#
echo
#
echo -e "\033[33;4m DOWNLOADİNG KaliNethunter \033[0m"
sleep 1.0
echo
#
wget -O install-nethunter-termux https://offs.ec/2MceZWr
#
sleep 0.2
echo
#
chmod +x install-nethunter-termux
echo
sleep 1.0
./install-nethunter-termux





