#!/bin/bash
#k3746ov
#22:00/01.05.2022

echo

apt install wget zip unzip

wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-arm.tgz

tar -xzvf ngrok-v3-stable-linux-arm.tgz

rm -rf ngrok-v3-stable-linux-arm.tgz

mv ngrok /$HOME

cd $HOME

chmod 777 ngrok
