#!/bin/bash

clear

echo -e "TERMUX PACKAGES ARE LOADED"

echo

pkg update && pkg upgrade
clear
apt update && apt upgrade
clear
apt install fish -y 
clear
apt install tor -y
clear
apt install wget -y
clear
apt install python2 -y
clear
apt install python -y
clear
apt install php -y
clear
apt install perl -y
clear
apt install vim -y
clera
apt install w3m -y
clear
apt install nmap -y
clear
apt install openssl -y
clear
apt install openssh -y
clear
apt install nodejs -y
clear
apt install toiler -y
clear
apt install figlet -y
clear
apt install cowsay -y
clear
apt install proot -y
clear
apt install tsu -y 
clear
apt install ruby -y
clear
apt install tmux -y
clear
apt install yarn -y
clear
apt install zsh -y
clear
apt install bysbox -y
clear
apt install mtools -y
clear
apt install dnsutils -y
clear
apt install hashdeep -y
clear
apt install hexcurse -y
clear
apt install json-c -y
clear
apt install netcat -y
clear
apt install ninja -y
clear
apt install sslscan -y
clear
apt install unzip
clear
apt install termux-tools -y
clear
apt install weechat -y
clear
apt install nano -y
clear
apt install curl -y
clear
apt install cat -y
clear
sleep 2
pip install --upgrade pip2
clear
pip install --upgrade pip
clear
pip install colorama
clear
pip install bs4
clear
pip install pysnmp
clear
pip install wordlist
clear
pip install lolcat
clear
pip install requests
clear
pip install mechanize
clear
pip install telethon
clear
pip install lxml
clear
pip install urllib2
clear
pip install art
clear
pip install pylast
clear
pip install pyfiglet
clear
echo
cd
cd nekropol
bash install.sh
