#!/bin/bash/
clear
pkg update && pkg upgrade 

rm -rf /data/data/com.termux/files/home/nekropol

rm -rf /data/data/com.termux/files/usr/nekropol

git clone https://github.com/k3746ov/nekropol

clear

/data/data/com.termux/files/home/nekropol/install
