#!/bin/bash
clear

print " \33[33mUpdate Nekropol ⚒\33[0m"

cd $HOME

rm -rf nekropol

pkg autoclean

git clone https://github.com/k3746ov/nekropol

cd $HOME/nekropol

chmod 777 install.sh

bash install.sh
