#!/bin/bash

pkg update && apt update && pkg upgrade && apt upgrade

clear

# Edit bash.bashrc File


clear /data/data/com.termux/files/usr/etc/motd

echo

cd $HOME && cd nekropol && cd Core && cd Banner

cat "banner.txt" >> /data/data/com.termux/files/usr/etc/bash.bashrc

$exit
$logout
